version: '3'
volumes:
  db:

services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: invoiceninja  
      MYSQL_USER: invoiceninjauser
      MYSQL_PASSWORD: ninja
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "8080:80"
    environment: []
    working_dir: /var/www/app/
    depends_on: 
      - db
    networks:
      - default
